### ISSUE TITLE
[Request] Conky Theme

### ISSUE THREAD

**Issue by ccarguelo** [mustafaozhan/Arc-Maia-Grey-Theme#2]
Hi, sorry I had to create and issue for this...

Do you mind sharing your conky? I first looked over [OpenDesktop](opendesktop.org) but could not find it.
So I thought asking you.

Thanks.

**Comment by mustafaozhan** [comment]
Hello,

Thank you for your interest I appreciate it 😄  Accualy I shared my configuration in [this](https://github.com/mustafaozhan/GoogleIntegratedSystemConky) repository. But you should wait for new commits because installation and readme is not completely ready right now. After your issue be sure that I will finish it before than I thought.

**Comment by mustafaozhan** [comment]
Hello,

I updated repository can you test and feedback to mr.mustafa.ozhan@gmail.com
